type Name {
    first: String!
    middle: String
    last: String!
}

type GameHistory {
    gameID: String!
    won: Boolean!
    tie: Boolean!
}

type Opponent{
    _id: ID!
    email: String!
    name: Name!
    signedupAt: String!
    currentGameID: String
    gameHistory: [GameHistory]
    permissions: [String]!
    allGameIDs: [String]
    resetPasswordExpire: String
    resetPasswordToken: String
}

type Move {
    fen: String!
    playedAt: String,
    _id: ID!
}

type Game{
    _id: ID!
    playerID: ID!
    moves: [Move]!
    playerToMove: Boolean!
    playerWon: Boolean!
    tied: Boolean!
}

type Query{
    getPlayerByEmail(email: String!) : Opponent!
    getPlayerById(id: String!): Opponent!
    getAllPlayers: [Opponent]!
    getGame(id: String!) : Game!
    testAuth: String!
}

type Mutation {
    createPlayer(firstName: String!, lastName: String!, middleName: String, email: String!, password: String!): String #JWT
    addMove(gameID: String!, fen: String!): Game!
    login(email: String!, password: String!): String #JWT
}