type Name {
    first: String!
    middle: String
    last: String!
}

type GameHistory {
    gameID: String!
    won: Boolean!
    tie: Boolean!
}

type Opponent{
    _id: ID!
    email: String!
    name: Name!
    signedupAt: String!
    currentGameID: String
    gameHistory: [GameHistory]
    permissions: [String]!
    allGameIDs: [String]
    resetPasswordExpire: String
    resetPasswordToken: String
    company: String,
    position: String,
    foundFrom: String
}

type Move {
    fen: String!
    playedAt: String,
    _id: ID!
}

type Game{
    _id: ID!
    playerID: ID!
    moves: [Move]!
    playerToMove: Boolean!
    playerWon: Boolean!
    tied: Boolean!
}

type AuthResponse {
    token: String
    message: String
}

type Query{
    getPlayerById(id: String!): Opponent!
    getPlayer: Opponent!
    getAllPlayers: [Opponent]!
    getGame(gameID: String!) : Game!
    testAuth: String!
}

type Mutation {
    register(email: String!, password: String!, firstName: String!, lastName: String!): AuthResponse! #JWT
    completeProfile(company: String, position: String, foundFrom: String) : AuthResponse!
    addMove(gameID: String!, fen: String!): Game!
    login(email: String!, password: String!): AuthResponse! #JWT
    forgotPassword(email: String!) : String # Reset token (for now)
    resetPassword(newPassword: String!, resetToken: String!) : String # Success message
}