type BlogInfo {
    id: String!
    lastEdited: String!
    name: String!
    timeline: String
    type: [String]
    languages: [String]
    frameworks: [String]
    github: String
    external: String
    description: String
    published: String
    isBlog: Boolean
    isProject: Boolean
    readTime: Int
}

type FilterParams {
    frameworks: [String]!
    type: [String]!
    languages: [String]!
}



type ContentBlock {
    type: String!
    content: [String]!
}

type YearData {
    title: String!
    description: String
}

type TimelineYear {
    year: Int!
    yearData: [YearData]!
}

type Query{
    hello: String!
    ProjectInfo: [BlogInfo]!
    BlogInfo(id: String): [BlogInfo]!
    FilterBy: FilterParams!
    TimelineInfo: [TimelineYear]!
    BlogContent(id: String!): [ContentBlock]!
}